[package]
name = "hanli"
version = "0.1.0"
authors = ["史成成 <shichengcheng-it@bestpay.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
